server:
  port: 3344

spring:
  application:
    name: mocroservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suoxuewu/microservicecloud-config.git #git上的地址