server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: /suoxuewu #设置统一公共前缀
  ignored-services: microservicecloud-dept #eureka真实服务名忽略
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydetp/**


info:
  app.name: atguigu-microcloud
  company.name: www.suoxuewu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
